# Week 2 - Mini Assessment

Welcome to you mini assessment for week two. For this assessment, you will be completing 15 exercises where for each new exercise, the difficulty level will only increase. You've got this! ðŸ˜Ž

At the end of an hour, we will walk over each question together. Feel free to post it on GitHub once you finish, under your respective folder for everything related to week 2.

1. import the numpy package and check its version.

In [ ]:
import numpy as np
 
np.__version__

'1.18.1'

2. Create an numpy range of values from 0 to 49 and name it `mynums`.

In [ ]:
mynums=np.arange(0,50)
mynums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

3. Reshape the array you created in step 2 into a matrix with the shape below and assign a copy of it to a variable called `my_matrix`.

In [ ]:
my_matrix=mynums.reshape(5,10)
my_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

4. Create a linearly-spaced array of size 100 between the numbers 20 to 100, assign it to the variable, `num_increases` and print it.

In [ ]:
num_increases=[np.linspace(20,100,100)]
print(num_increases)

5. Create an numpy array with 20 zeros, assign it to the variable `zeroes`.

In [ ]:
zeroes=np.zeros(20,dtype='int8')
#zeroes=np.zeros(20)
print(zeroes)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

6. Create a two dimensional array of size 7 by 8 filled with 1s and do the following:
- mulptiply the first row by 2
- add 3 and raise to the power of two the odd columns starting from the beginning
- subtract 10 and multiply by 15 the elements in the even rows and odd columns

In [ ]:
matrix_six=np.ones((7,8),dtype='int8')
matrix_six_copy=matrix_six
matrix_six[0,:]=matrix_six[0,:]*2
print(matrix_six)

7. Create a numpy array starting with 20 and ending with 40 with 10 equally spaced values.

In [ ]:
#matrix_seven=np.arange(20,40,2)
matrix_seven=np.linspace(20,40,10)
print(matrix_seven)

8. Create a 9 by 9 matrix with random integers from 100 to 500 and use the dtype "int32".

In [ ]:
matrix_eight=np.array([
                    np.random.randint(100,500,81,dtype='int32')
                    ]).reshape(9,9)

print(matrix_eight)

9. Create an empty array of 20 elements with shape 2 by 10, dtype 'float32' and add a different number to each row.

In [ ]:
matrix_nine=np.empty((2,10),dtype='float32')
matrix_nine[0:]=matrix_nine[0:]+2
matrix_nine[1:]=matrix_nine[1:]+3
print(array_nine)

[[ 0.00000000e+00  2.81250000e+00 -2.27893146e-30  2.84722209e+00
   7.99975539e-22  2.88194442e+00 -3.03164910e-13  2.91666651e+00
   1.08506945e-04  2.95138884e+00]
 [-4.00497773e+04  2.98611093e+00 -3.03164910e-13  3.01041651e+00
   1.97190097e+30  3.02777767e+00  1.08506945e-04  3.04513884e+00
   0.00000000e+00  3.06250000e+00]]

10. Create an array with 15 random numbers between 100 and 200 and print the maximum value in the array.

In [ ]:
matrix_ten=np.arange(101,200,7)
#matrix_ten=np.random.random(100,20,15)
print(matrix_ten)
print(max(matrix_ten))

[101 108 115 122 129 136 143 150 157 164 171 178 185 192 199]
199

11. Create an array with the following numbers [40, 41, 26, 14, 15, 47, 43, 33, 44, 22], select the 5th to 10th elements, assign each to a new variable, change their value, and then print all 3 (the first array and your next two variables.

In [ ]:
matrix_eleven=np.array([40,41,26,14,15,47,43,33,44,22])
no_5=matrix_eleven[4]
no_10=matrix_eleven[9]
no_5=60
no_10=70
print(matrix_eleven)
print(no_5)
print(no_10)

12. Create an array of 360 random numbers from -10 to 50 (to resemble the weather) and find the min, max, 25th percentile, 75 percentile, and the median.

In [ ]:
array_12 = np.random.randint(-10, 50, 360)
print(f"Min:{np.min(array_12)}")
print(f"Max:{np.max(array_12)}")
print(f"25th percentile:{np.percentile(array_12,25)}")
print(f"75th percentile:{np.percentile(array_12,75)}")
print(f"Median:{np.median(array_12)}")

13. Reshape the array you created in step 12 into a matrix of 300 by 12 ad get the same values but only for the months this time.

In [ ]:
array_13=array_12.reshape(30,12)
print(array_13)

14. Create a mask for your data, and filter out and print:
- average temperature of the days where the temperature was below 10
- average temperature of the days where the temperature was greater than 30

In [ ]:
print(f"Avg. tempature below 10:{np.average(array_13[(array_13<10)])}")
print(f"Avg. temperature greater than 30: {np.average(array_13[(array_13>30)])}")

Avg. tempature below 10:-0.26956521739130435
Avg. temperature greater than 30: 40.36448598130841

15. Create a full 10 by 10 matrix with a number of your choosing and assign it to a variable. After printing that variables, unravel the matrix and assign the array to a new number.

In [ ]:
matrix_15=np.full((10,10),5)
print(matrix_15)
matrix_15_new=matrix_15.ravel()
matrix_15_new[:]=7
print(matrix_15_new)